base_config:
  - configs/base.yaml

task_cls: src.acoustic_task.AcousticTask
datasets: [
  'opencpop',
]
num_spk: 1
test_prefixes: [
    '2044',
    '2086',
    '2092',
    '2093',
    '2100',
]

vocoder: NsfHifiGAN
vocoder_ckpt: checkpoints/nsf_hifigan/model
use_nsf: true
audio_sample_rate: 44100
audio_num_mel_bins: 128
hop_size: 512            # Hop size.
fft_size: 2048           # FFT size.
win_size: 2048           # FFT size.
fmin: 40
fmax: 16000
min_level_db: -120

binarization_args:
  with_wav: false
  with_spk_embed: false
  with_align: true
  shuffle: true
#augmentation_args:
#  random_pitch_shifting:
#    range: [-5., 5.]
#    scale: 1.0
#  fixed_pitch_shifting:
#    targets: [-5., 5.]
#    scale: 0.75
#  random_time_stretching:
#    range: [0.5, 2.]
#    domain: log  # or linear
#    scale: 2.0

raw_data_dir: 'data/opencpop/raw'
binary_data_dir: 'data/opencpop/binary'
binarizer_cls: data_gen.acoustic.AcousticBinarizer
g2p_dictionary: dictionaries/opencpop-extension.txt
pitch_type: frame
spec_min: [-5]
spec_max: [0]
keep_bins: 128
mel_loss: "ssim:0.5|l1:0.5"
mel_vmin: -6. #-6.
mel_vmax: 1.5
save_f0: true

#pe_enable: true
#pe_ckpt: 'checkpoints/0102_xiaoma_pe'
max_frames: 8000
use_uv: false
use_midi: false
use_spk_embed: false
use_spk_id: false
use_key_shift_embed: false
use_speed_embed: false
use_gt_f0: false  #  for midi exp
use_gt_dur: false  # for further midi exp
f0_embed_type: continuous

K_step: 1000
timesteps: 1000
max_beta: 0.02
rel_pos: true
gaussian_start: true
pndm_speedup: 10
hidden_size: 256
residual_layers: 20
residual_channels: 384
dilation_cycle_length: 4  # *
diff_decoder_type: 'wavenet'
diff_loss_type: l2
schedule_type: 'linear'

# train and eval
num_sanity_val_steps: 1
lr: 0.0004
decay_steps: 50000
gamma: 0.5
max_tokens: 80000
max_sentences: 48
val_check_interval: 2000
num_valid_plots: 10
max_updates: 320000
permanent_ckpt_start: 120000
permanent_ckpt_interval: 40000
