base_config:
  - configs/base.yaml

task_cls: training.variance_task.VarianceTask
num_spk: 1
speakers:
  - opencpop
test_prefixes: [
    '2044',
    '2086',
    '2092',
    '2093',
    '2100',
]

audio_sample_rate: 44100
hop_size: 512            # Hop size.
midi_smooth_width: 0.2  # in seconds

binarization_args:
  shuffle: true
  num_workers: 0

raw_data_dir: 'data/opencpop_variance/raw'
binary_data_dir: 'data/opencpop_variance/binary'
binarizer_cls: preprocessing.variance_binarizer.VarianceBinarizer
dictionary: dictionaries/opencpop-extension.txt

use_spk_id: false

K_step: 1000
timesteps: 1000
max_beta: 0.02
rel_pos: true
diff_accelerator: dpm-solver
pndm_speedup: 10

hidden_size: 256

predict_dur: true
dur_cascade: false
lambda_dur_loss: 1.0
dur_prediction_args:
  hidden_size: 384
  dropout: 0.1
  num_layers: 5
  kernel_size: 3
  log_offset: 1.0
  loss_type: mse
  lambda_pdur_loss: 0.3
  lambda_wdur_loss: 1.0
  lambda_sdur_loss: 3.0

predict_pitch: true
pitch_cascade: true
lambda_pitch_loss: 1.0
pitch_prediction_args:
  diff_predictor_mode: repeat
  pitch_delta_vmin: -12  # -12.75
  pitch_delta_vmax: 12  # 12.75
  num_pitch_bins: 64
  deviation: 0.25
  hidden_size: 512
  residual_layers: 20
  residual_channels: 256

residual_layers: 10
residual_channels: 256
dilation_cycle_length: 5  # *
diff_decoder_type: 'wavenet'
diff_loss_type: l2
schedule_type: 'linear'

# train and eval
num_sanity_val_steps: 1
optimizer_args:
  lr: 0.0004
lr_scheduler_args:
  step_size: 50000
  gamma: 0.5
max_batch_frames: 80000
max_batch_size: 48
val_with_vocoder: true
val_check_interval: 500
num_valid_plots: 10
max_updates: 320000
num_ckpt_keep: 5
permanent_ckpt_start: 120000
permanent_ckpt_interval: 40000
