base_config:
  - configs/base.yaml

task_cls: training.variance_task.VarianceTask
num_spk: 1
speakers:
  - opencpop
test_prefixes: [
    '2044',
    '2086',
    '2092',
    '2093',
    '2100',
]

audio_sample_rate: 44100
hop_size: 512            # Hop size.

binarization_args:
  shuffle: true
  num_workers: 0

raw_data_dir: 'data/opencpop_variance/raw'
binary_data_dir: 'data/opencpop_variance/binary'
binarizer_cls: preprocessing.variance_binarizer.VarianceBinarizer
dictionary: dictionaries/opencpop-extension.txt

use_spk_id: false

K_step: 1000
timesteps: 1000
max_beta: 0.02
rel_pos: true
pndm_speedup: 10

hidden_size: 256
predictor_hidden: 384
predictor_dropout: 0.1
dur_predictor_kernel: 3
dur_predictor_layers: 2

residual_layers: 20
residual_channels: 384
dilation_cycle_length: 4  # *
diff_decoder_type: 'wavenet'
diff_loss_type: l2
schedule_type: 'linear'

# train and eval
num_sanity_val_steps: 1
lr: 0.0004
lr_decay_steps: 50000
lr_decay_gamma: 0.5
max_batch_frames: 80000
max_batch_size: 48
val_with_vocoder: true
val_check_interval: 2000
num_valid_plots: 10
max_updates: 320000
permanent_ckpt_start: 120000
permanent_ckpt_interval: 40000
